# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBNt2NiXJKL6GzgMPqfVFcmoP4ukl5ml
"""

total = 0
for i in range (1,101) :
  total += i
print ("Sum:", total)