# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLtc6QwEv_LS88YjppEk8dbQGKhRprFE
"""

count = 1
while count <= 5 :
  print ("Count:",count)
  count += 1