# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M51bAsFOq0Z70fwP3wKy86Lgwu0eVCwq
"""

for i in range (5) :
  print ("Hello",i)