# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVh1XyKdmAPY8FXXoXAQsb21a4BHTMDq
"""

for i in range (1, 11) :
  print (i)