# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkvruIqZ1Z0-Xd6MswIy6Ms4GMGEOOux
"""

name = "Prachi"

for letter in name:
    print(letter)