# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nObNo3-EHe8073xJfu5n76DDA7plemjS
"""

secret_number = 17
guess = None

while guess != secret_number:
    guess = int(input("Enter the number: "))

    if guess < secret_number:
      print("Too Low")
    elif guess > secret_number:
      print("Too High")
    else:
       print("It's right!")