# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYu0AG1HlV8e4gT4VCI7QvczP40x4xCy
"""

table = 10
while table <= 100 :
  print (table)
  table += 10