# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vM_w8GlZc-BMYGxA1w0kIbon14DhDnx
"""

for i in range (10) :
  if i % 2 == 0 :
    continue
  print (i)