# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_ilVK0UjG8po2pEZgd8OkeDXY3lB7-Z
"""

num = 2
while num <= 20 :
  print (num)
  num += 2