# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGWnRpTTn24kmYi8kmxMvgSruti-kMrL
"""

num = 10
for i in range(1, 11):
    print(num, "x", i, "=", num * i)