# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCJQM6xbjJBeVNxSmPCkvVRxshAo5LUo
"""

for i in range (10) :
  if i == 5 :
    break
  print(i)