# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yENWUC5m0NhM-Wa84vanCI77xmaPuRyn
"""

for i in range (5) :
  print (i)

for i in range (2,6) :
  print (i)

for i in range (0,10,2) :
  print (i)